---

# Homebrew
- name: Install dev tools (Homebrew)
  homebrew: name={{ item }} state=present
  become: true
  become_user: "{{ dev_tools_homebrew_user }}"
  with_items:
    - ansible
    - libxml2
    - libxslt
    - ruby
    - sqlite
  when: ansible_pkg_mgr == 'homebrew'

# Other package managers
- fail: msg="{{ ansible_pkg_mgr }} is not a supported package manager (Homebrew is supported)"
  when: ansible_pkg_mgr != 'homebrew'
