---

# Homebrew
- name: Install dev tools (Homebrew)
  homebrew:
    name:
      - ansible
      - composer
      - cmake
      - ctags
      - gcc
      - gradle
      - heroku/brew/heroku
      - libxml2
      - libxslt
      - openshift-cli
      - protobuf
      - protobuf-c
      - rabbitmq
      - sqlite
      - upx
      # Also install the latest version of some programming languages with
      # Homebrew, in case some tool does not have the PATH set up correctly for
      # asdf.
      - elm
      - node
      - python
      - python3
      - ruby
      - typescript
    state: present
  become: true
  become_user: "{{ dev_tools_homebrew_user }}"
  when: ansible_pkg_mgr == 'homebrew'

# Other package managers
- fail: msg="{{ ansible_pkg_mgr }} is not a supported package manager (Homebrew is supported)"
  when: ansible_pkg_mgr != 'homebrew'
